#!/usr/bin/env python
# -*- coding: utf-8-unix -*-

def get_simplify_mapping():
    # In the Orchestration_checked folder, midi files are associated to csv files
    # This script aims at reducing the number of instrument written in the csv files
    # by grouping together different but close instruments ()

    # simplify_mapping = {
    #     "Piccolo": "Flute",
    #     "Flute": "Flute",
    #     "Alto-Flute": "Flute",
    #     "Soprano-Flute": "Flute",
    #     "Bass-Flute": "Flute",
    #     "Contrabass-Flute": "Flute",
    #     "Pan Flute": "Flute",
    #     "Recorder": "Flute",
    #     "Ocarina": "Remove",
    #     "Oboe": "Oboe",
    #     "Oboe-dAmore": "Oboe",
    #     "Oboe de Caccia": "Oboe",
    #     "English-Horn": "Horn",
    #     "Heckelphone": "Remove",
    #     "Piccolo-Clarinet-Ab": "Clarinet",
    #     "Clarinet": "Clarinet",
    #     "Clarinet-Eb": "Clarinet",
    #     "Clarinet-Bb": "Clarinet",
    #     "Piccolo-Clarinet-D": "Clarinet",
    #     "Clarinet-C": "Clarinet",
    #     "Clarinet-A": "Clarinet",
    #     "Basset-Horn-F": "Horn",
    #     "Alto-Clarinet-Eb": "Clarinet",
    #     "Bass-Clarinet-Bb": "Clarinet",
    #     "Bass-Clarinet-A": "Clarinet",
    #     "Contra-Alto-Clarinet-Eb": "Clarinet",
    #     "Contrabass-Clarinet-Bb": "Clarinet",
    #     "Bassoon": "Bassoon",
    #     "Contrabassoon": "Bassoon",
    #     "Soprano-Sax": "Sax",
    #     "Alto-Sax": "Sax",
    #     "Tenor-Sax": "Sax",
    #     "Baritone-Sax": "Sax",
    #     "Bass-Sax": "Sax",
    #     "Contrabass-Sax": "Sax",
    #     "Horn": "Horn",
    #     "Harmonica": "Remove",
    #     "Piccolo-Trumpet-Bb": "Trumpet",
    #     "Piccolo-Trumpet-A": "Trumpet",
    #     "High-Trumpet-F": "Trumpet",
    #     "High-Trumpet-Eb": "Trumpet",
    #     "High-Trumpet-D": "Trumpet",
    #     "Cornet": "Trumpet",
    #     "Trumpet": "Trumpet",
    #     "Trumpet-C": "Trumpet",
    #     "Trumpet-Bb": "Trumpet",
    #     "Cornet-Bb": "Trumpet",
    #     "Alto-Trumpet-F": "Trumpet",
    #     "Bass-Trumpet-Eb": "Trumpet",
    #     "Bass-Trumpet-C": "Trumpet",
    #     "Bass-Trumpet-Bb": "Trumpet",
    #     "Clarion": "Trumpet",
    #     "Trombone": "Trombone",
    #     "Alto-Trombone": "Trombone",
    #     "Soprano-Trombone": "Trombone",
    #     "Tenor-Trombone": "Trombone",
    #     "Bass-Trombone": "Trombone",
    #     "Contrabass-Trombone": "Trombone",
    #     "Euphonium": "Remove",
    #     "Tuba": "Tuba",
    #     "Bass-Tuba": "Tuba",
    #     "Contrabass-Tuba": "Tuba",
    #     "Flugelhorn": "Remove",
    #     "Piano": "Piano",
    #     "Celesta": "Remove",
    #     "Organ": "Organ",
    #     "Harpsichord": "Piano",
    #     "Accordion": "Accordion",
    #     "Bandoneone": "Remove",
    #     "Harp": "Harp",
    #     "Guitar": "Guitar",
    #     "Bandurria": "Guitar",
    #     "Mandolin": "Guitar",
    #     "Lute": "Remove",
    #     "Lyre": "Remove",
    #     "Strings": "Remove",
    #     "Violin": "Violin",
    #     "Violins": "Violin",
    #     "Viola": "Viola",
    #     "Violas": "Viola",
    #     "Viola de gamba": "Viola",
    #     "Viola de braccio": "Remove",
    #     "Violoncello": "Violoncello",
    #     "Violoncellos": "Violoncello",
    #     "Contrabass": "Contrabass",
    #     "Basso continuo": "Remove",
    #     "Bass drum": "Remove",
    #     "Glockenspiel": "Remove",
    #     "Xylophone": "Remove",
    #     "Vibraphone": "Remove",
    #     "Marimba": "Remove",
    #     "Maracas": "Remove",
    #     "Bass-Marimba": "Remove",
    #     "Tubular-Bells": "Remove",
    #     "Clave": "Remove",
    #     "Bombo": "Remove",
    #     "Hi-hat": "Remove",
    #     "Triangle": "Remove",
    #     "Ratchet": "Remove",
    #     "Drum": "Remove",
    #     "Snare drum": "Remove",
    #     "Steel drum": "Remove",
    #     "Tambourine": "Remove",
    #     "Tam tam": "Remove",
    #     "Timpani": "Remove",
    #     "Cymbal": "Remove",
    #     "Castanets": "Remove",
    #     "Percussion": "Remove",
    #     "Voice": "Voice",
    #     "Voice soprano": "Voice",
    #     "Voice mezzo": "Voice",
    #     "Voice alto": "Voice",
    #     "Voice contratenor": "Voice",
    #     "Voice tenor": "Voice",
    #     "Voice baritone": "Voice",
    #     "Voice bass": "Voice",
    #     "Ondes martenot": "Remove",
    #     "Unknown": "Remove",
    # }

    #################################################
    #################################################
    #################################################
    #################################################
    # Violin : G3-C7
    # Viola : C3-E6
    # Cello : C2-C6
    # D-bass : C1-C4
    # VERSION HARDCORE QUATUOR
    # simplify_mapping = {
    #     "Piccolo": "Violin",
    #     "Flute": "Violin",
    #     "Alto-Flute": "Violin",
    #     "Soprano-Flute": "Violin",
    #     "Bass-Flute": "Viola",
    #     "Contrabass-Flute": "Violoncello",
    #     "Pan Flute": "Remove",
    #     "Recorder": "Violin",
    #     "Ocarina": "Remove",
    #     "Oboe": "Violin",
    #     "Oboe-dAmore": "Violin",
    #     "Oboe de Caccia": "Remove",
    #     "English-Horn": "Viola",
    #     "Heckelphone": "Remove",
    #     "Piccolo-Clarinet-Ab": "Violin",
    #     "Clarinet": "Violin",
    #     "Clarinet-Eb": "Violin",
    #     "Clarinet-Bb": "Violin",
    #     "Piccolo-Clarinet-D": "Violin",
    #     "Clarinet-C": "Violin",
    #     "Clarinet-A": "Violin",
    #     "Basset-Horn-F": "Contrabass",
    #     "Alto-Clarinet-Eb": "Violoncello",
    #     "Bass-Clarinet-Bb": "Contrabass",
    #     "Bass-Clarinet-A": "Contrabass",
    #     "Contra-Alto-Clarinet-Eb": "Contrabass",
    #     "Contrabass-Clarinet-Bb": "Contrabass",
    #     "Bassoon": "Contrabass",
    #     "Contrabassoon": "Contrabass",
    #     "Soprano-Sax": "Violin",
    #     "Alto-Sax": "Viola",
    #     "Tenor-Sax": "Violoncello",
    #     "Baritone-Sax": "Violoncello",
    #     "Bass-Sax": "Contrabass",
    #     "Contrabass-Sax": "Contrabass",
    #     "Horn": "Contrabass",
    #     "Harmonica": "Remove",
    #     "Piccolo-Trumpet-Bb": "Violin",
    #     "Piccolo-Trumpet-A": "Violin",
    #     "High-Trumpet-F": "Violin",
    #     "High-Trumpet-Eb": "Violin",
    #     "High-Trumpet-D": "Violin",
    #     "Cornet": "Viola",
    #     "Trumpet": "Viola",
    #     "Trumpet-C": "Viola",
    #     "Trumpet-Bb": "Viola",
    #     "Cornet-Bb": "Viola",
    #     "Alto-Trumpet-F": "Viola",
    #     "Bass-Trumpet-Eb": "Violoncello",
    #     "Bass-Trumpet-C": "Violoncello",
    #     "Bass-Trumpet-Bb": "Violoncello",
    #     "Clarion": "Remove",
    #     "Trombone": "Violin and Viola and Violoncello and Contrabass",
    #     "Alto-Trombone": "Violoncello",
    #     "Soprano-Trombone": "Viola",
    #     "Tenor-Trombone": "Contrabass",
    #     "Bass-Trombone": "Contrabass",
    #     "Contrabass-Trombone": "Trombone",
    #     "Euphonium": "Remove",
    #     "Tuba": "Contrabass",
    #     "Bass-Tuba": "Contrabass",
    #     "Contrabass-Tuba": "Contrabass",
    #     "Flugelhorn": "Remove",
    #     "Piano": "Piano",
    #     "Celesta": "Remove",
    #     "Organ": "Violin and Viola and Violoncello and Contrabass",
    #     "Harpsichord": "Violin and Viola and Violoncello and Contrabass",
    #     "Accordion": "Remove",
    #     "Bandoneone": "Remove",
    #     "Harp": "Remove",
    #     "Guitar": "Remove",
    #     "Bandurria": "Remove",
    #     "Mandolin": "Remove",
    #     "Lute": "Remove",
    #     "Lyre": "Remove",
    #     "Strings": "Violin and Viola and Violoncello and Contrabass",
    #     "Violin": "Violin",
    #     "Violins": "Violin",
    #     "Viola": "Viola",
    #     "Violas": "Viola",
    #     "Viola de gamba": "Viola",
    #     "Viola de braccio": "Remove",
    #     "Violoncello": "Violoncello",
    #     "Violoncellos": "Violoncello",
    #     "Contrabass": "Contrabass",
    #     "Basso continuo": "Remove",
    #     "Bass drum": "Remove",
    #     "Glockenspiel": "Remove",
    #     "Xylophone": "Remove",
    #     "Vibraphone": "Remove",
    #     "Marimba": "Remove",
    #     "Maracas": "Remove",
    #     "Bass-Marimba": "Remove",
    #     "Tubular-Bells": "Remove",
    #     "Clave": "Remove",
    #     "Bombo": "Remove",
    #     "Hi-hat": "Remove",
    #     "Triangle": "Remove",
    #     "Ratchet": "Remove",
    #     "Drum": "Remove",
    #     "Snare drum": "Remove",
    #     "Steel drum": "Remove",
    #     "Tambourine": "Remove",
    #     "Tam tam": "Remove",
    #     "Timpani": "Remove",
    #     "Cymbal": "Remove",
    #     "Castanets": "Remove",
    #     "Percussion": "Remove",
    #     "Voice": "Violin and Viola and Violoncello and Contrabass",
    #     "Voice soprano": "Violin",
    #     "Voice mezzo": "Viola",
    #     "Voice alto": "Viola",
    #     "Voice contratenor": "Viola",
    #     "Voice tenor": "Violoncello",
    #     "Voice baritone": "Violoncello",
    #     "Voice bass": "Contrabass",
    #     "Ondes martenot": "Remove",
    #     "Unknown": "Remove",
    # }

    simplify_mapping = {
        "Piccolo": "Flute",
        "Flute": "Flute",
        "Alto-Flute": "Flute",
        "Soprano-Flute": "Flute",
        "Tenor-Flute": "Flute",
        "Bass-Flute": "Flute",
        "Contrabass-Flute": "Flute",
        "Flauto dAmore": "Flute",   # Tenor flute
        "Pan Flute": "Remove",
        "Recorder": "Remove",
        "Ocarina": "Remove",
        "Oboe": "Oboe",
        "Oboe-dAmore": "Oboe",
        "Oboe de Caccia": "Oboe",
        "English-Horn": "Oboe",
        "Heckelphone": "Remove",
        "Piccolo-Clarinet-Ab": "Clarinet",
        "Clarinet": "Clarinet",
        "Clarinet-Eb": "Clarinet",
        "Clarinet-Bb": "Clarinet",
        "Piccolo-Clarinet-D": "Clarinet",
        "Clarinet-C": "Clarinet",
        "Clarinet-A": "Clarinet",
        "Basset-Horn-F": "Clarinet",
        "Alto-Clarinet-Eb": "Clarinet",
        "Bass-Clarinet-Bb": "Clarinet",
        "Bass-Clarinet-A": "Clarinet",
        "Contra-Alto-Clarinet-Eb": "Clarinet",
        "Contrabass-Clarinet-Bb": "Clarinet",
        "Bassoon": "Bassoon",
        "Contrabassoon": "Bassoon",
        "Soprano-Sax": "Remove",
        "Alto-Sax": "Remove",
        "Tenor-Sax": "Remove",
        "Baritone-Sax": "Remove",
        "Bass-Sax": "Remove",
        "Contrabass-Sax": "Remove",
        "Horn": "Horn",
        "Harmonica": "Remove",
        "Piccolo-Trumpet-Bb": "Trumpet",
        "Piccolo-Trumpet-A": "Trumpet",
        "High-Trumpet-F": "Trumpet",
        "High-Trumpet-Eb": "Trumpet",
        "High-Trumpet-D": "Trumpet",
        "Cornet": "Trumpet",
        "Trumpet": "Trumpet",
        "Trumpet-C": "Trumpet",
        "Trumpet-Bb": "Trumpet",
        "Cornet-Bb": "Trumpet",
        "Alto-Trumpet-F": "Trumpet",
        "Bass-Trumpet-Eb": "Trumpet",
        "Bass-Trumpet-C": "Trumpet",
        "Bass-Trumpet-Bb": "Trumpet",
        "Clarion": "Remove",
        "Trombone": "Trombone",
        "Alto-Trombone": "Trombone",
        "Soprano-Trombone": "Trombone",
        "Tenor-Trombone": "Trombone",
        "Bass-Trombone": "Trombone",
        "Contrabass-Trombone": "Trombone",
        "Euphonium": "Tuba",
        "Tuba": "Tuba",
        "Bass-Tuba": "Tuba",
        "Contrabass-Tuba": "Tuba",
        "Flugelhorn": "Trumpet",
        "Piano": "Piano",
        "Celesta": "Remove",
        "Organ": "Remove",
        "Harpsichord": "Remove",
        "Accordion": "Remove",
        "Bandoneone": "Remove",
        "Harp": "Harp",
        "Guitar": "Harp",
        "Bandurria": "Harp",
        "Mandolin": "Harp",
        "Lute": "Harp",
        "Lyre": "Harp",
        "Strings": "Violin and Viola and Violoncello and Contrabass",
        "Violin": "Violin",
        "Violins": "Violin",
        "Viola": "Viola",
        "Violas": "Viola",
        "Viola de gamba": "Viola",
        "Viola de braccio": "Remove",
        "Viola dAmore": "Remove",
        "Violoncello": "Violoncello",
        "Violoncellos": "Violoncello",
        "Contrabass": "Contrabass",
        "Basso continuo": "Remove",
        "Bass drum": "Remove",
        "Glockenspiel": "Remove",
        "Xylophone": "Remove",
        "Vibraphone": "Remove",
        "Marimba": "Remove",
        "Maracas": "Remove",
        "Bass-Marimba": "Remove",
        "Tubular-Bells": "Remove",
        "Clave": "Remove",
        "Bombo": "Remove",
        "Hi-hat": "Remove",
        "Triangle": "Remove",
        "Ratchet": "Remove",
        "Drum": "Remove",
        "Snare drum": "Remove",
        "Steel drum": "Remove",
        "Tambourine": "Remove",
        "Tam tam": "Remove",
        "Timpani": "Timpani",
        "Cymbal": "Remove",
        "Castanets": "Remove",
        "Percussion": "Remove",
        "Voice": "Remove",
        "Voice soprano": "Remove",
        "Voice mezzo": "Remove",
        "Voice alto": "Remove",
        "Voice contratenor": "Remove",
        "Voice tenor": "Remove",
        "Voice baritone": "Remove",
        "Voice bass": "Remove",
        "Ondes martenot": "Remove",
        "Unknown": "Remove",
    }
    #################################################
    #################################################
    #################################################
    #################################################
    return simplify_mapping

# def group_instrument_mxml():
#     ret = {
#         "A Clarinet": "Clarinet",
#         "Alto": "Remove",
#         "Alto Flute": "Flute",
#         "Alto Recorder": "Remove",
#         "B Clarinet": "Clarinet",
#         "B Trumpet": "Trumpet",
#         "Baritone": "Remove",
#         "Bass": "Remove",
#         "Bass Clarinet": "Clarinet",
#         "Bass Recorder": "Remove",
#         "Bass Trombone": "Trombone",
#         "Basso Continuo": "Remove",
#         "Bassoon": "Bassoon",
#         "Castanets": "Percussion",
#         "Celesta": "Remove",
#         "Chinese Cymbal": "Remove",
#         "Clarinet": "Clarinet",
#         "Contrabass": "Contrabass",
#         "Contrabass Recorder": "Remove",
#         "Contrabasse": "Contrabass",
#         "Contrabasses": "Contrabass",
#         "Contrabassoon": "Bassoon",
#         "Contrabbass": "Contrabass",
#         "Crash Cymbal 1": "Remove",
#         "English Horn": "Oboe",
#         "Fagotti": "Bassoon",
#         "Flauti": "Flute",
#         "Flute": "Flute",
#         "Euphonium": "Tuba",
#         "Basso continuo": "Remove",
#         "Glockenspiel": "Remove",
#         "Harp": "Harp",
#         "Harpsichord": "Remove",
#         "High C Horn": "Horn",
#         "Horn": "Horn",
#         "Horn in B basso": "Horn",
#         "Horn in F": "Horn",
#         "Instrument 82": "Percussion",
#         "Instrument 89": "Percussion",
#         "Low Conga": "Percussion",
#         "Oboe": "Oboe",
#         "Open Triangle": "Percussion",
#         "Organ": "Remove",
#         "Pan Flute": "Remove",
#         "Percussion": "Percussion",
#         "Piano": "Piano",
#         "Piccolo": "Flute",
#         "Piccolo Trumpet in B": "Remove",
#         "Recorder": "Remove",
#         "Snare Drum 2": "Percussion",
#         "Soprano": "Remove",
#         "Strings": "Violin and Viola and Violoncello and Contrabass",
#         "Tam-Tam": "Percussion",
#         "Tambourine": "Percussion",
#         "Tenor": "Remove",
#         "Tenor Recorder": "Remove",
#         "Timpani": "Timpani",
#         "Treble Flute": "Flute",
#         "Trombone": "Trombone",
#         "Bass-Trombone": "Trombone",
#         "Trumpet": "Trumpet",
#         "Tuba": "Tuba",
#         "Unknown": "Remove",
#         "Vienna Horn": "Horn",
#         "Viola": "Viola",
#         "Violas": "Viola",
#         "Violin": "Violin",
#         "Violins": "Violin",
#         "Violoncello": "Violoncello",
#         "Violoncellos": "Violoncello",
#         "Voice": "Remove",
#         "Voice soprano": "Remove",
#         "Voice alto": "Remove",
#         "Voice tenor": "Remove",
#         "Voice bass": "Remove",
#         "Voice baritone": "Remove",
#         "Cymbal": "Remove",
#         "Women": "Remove"
#     }
#     return ret

if __name__ == "__main__":
    simplify_mapping = get_simplify_mapping()
    import pdb; pdb.set_trace()