program_change_mapping = {
    "Piccolo": 73,
    "Flute": 74,
    "Alto-Flute": 74,
    "Soprano-Flute": 74,
    "Bass-Flute": 74,
    "Contrabass-Flute": 74,
    "Pan Flute": 76,
    "Recorder": 74,
    "Ocarina": 80,
    "Oboe": 69,
    "Oboe-dAmore": 69,
    "Oboe de Caccia": 69,
    "English-Horn": 70,
    "Heckelphone": 0,
    "Piccolo-Clarinet-Ab": 72,
    "Clarinet": 72,
    "Clarinet-Eb": 72,
    "Clarinet-Bb": 72,
    "Piccolo-Clarinet-D": 72,
    "Clarinet-C": 72,
    "Clarinet-A": 72,
    "Basset-Horn-F": 61,
    "Alto-Clarinet-Eb": 72,
    "Bass-Clarinet-Bb": 72,
    "Bass-Clarinet-A": 72,
    "Contra-Alto-Clarinet-Eb": 72,
    "Contrabass-Clarinet-Bb": 72,
    "Bassoon": 71,
    "Contrabassoon": 71,
    "Soprano-Sax": 65,
    "Alto-Sax": 66,
    "Tenor-Sax": 67,
    "Baritone-Sax": 68,
    "Bass-Sax": 68,
    "Contrabass-Sax": 68,
    "Horn": 61,
    "Harmonica": 23,
    "Piccolo-Trumpet-Bb": 57,
    "Piccolo-Trumpet-A": 57,
    "High-Trumpet-F": 57,
    "High-Trumpet-Eb": 57,
    "High-Trumpet-D": 57,
    "Cornet": 57,
    "Trumpet": 57,
    "Trumpet-C": 57,
    "Trumpet-Bb": 57,
    "Cornet-Bb": 57,
    "Alto-Trumpet-F": 57,
    "Bass-Trumpet-Eb": 57,
    "Bass-Trumpet-C": 57,
    "Bass-Trumpet-Bb": 57,
    "Clarion": 57,
    "Trombone": 58,
    "Alto-Trombone": 58,
    "Soprano-Trombone": 58,
    "Tenor-Trombone": 58,
    "Bass-Trombone": 58,
    "Contrabass-Trombone": 58,
    "Euphonium": 59,
    "Tuba": 59,
    "Bass-Tuba": 59,
    "Contrabass-Tuba": 59,
    "Flugelhorn": 0,
    "Piano": 1,
    "Celesta": 9,
    "Organ": 20,
    "Harpsichord": 7,
    "Accordion": 22,
    "Bandoneone": 22,
    "Harp": 47,
    "Guitar": 25,
    "Bandurria": 25,
    "Mandolin": 25,
    "Lute": 25,
    "Lyre": 25,
    "Violin": 41,
    "Violins": 41,
    "Viola": 42,
    "Violas": 42,
    "Viola de gamba": 42,
    "Viola de braccio": 42,
    "Violoncello": 43,
    "Violoncellos": 43,
    "Contrabass": 44,
    "Basso continuo": 44,
    "Bass drum": 35,
    "Glockenspiel": 10,
    "Xylophone": 14,
    "Vibraphone": 12,
    "Marimba": 13,
    "Maracas": 70,
    "Bass-Marimba": 13,
    "Tubular-Bells": 15,
    "Clave": 75,
    "Bombo": 0,
    "Hi-hat": 42,
    "Triangle": 81,
    "Ratchet": 0,
    "Drum": 0,
    "Snare drum": 38,
    "Steel drum": 115,
    "Tambourine": 54,
    "Tam tam": 54,
    "Timpani": 48,
    "Cymbal": 49,
    "Castanets": 0,
    "Percussion": 0,
    "Voice": 54,
    "Voice soprano": 54,
    "Voice mezzo": 54,
    "Voice alto": 54,
    "Voice contratenor": 54,
    "Voice tenor": 54,
    "Voice baritone": 54,
    "Voice bass": 54,
    "Ondes martenot": 0,
    "Unknown": 0,
}